#include "CMT2380F32_Demo.h"

word SysTime;
FlagSTR  _System_F;
byte Prodution_ID[3];

byte TX_Buf[64];

word ResetTime;
FlagSTR  		_LedTime;

//;---------------------------------------
//;  CMT2300A Configuration File
//;  Generated by CMOSTEK RFPDK 1.51
//;  2020.06.11 15:44
//;---------------------------------------
//; Mode                      = Advanced
//; Part Number               = CMT2300A
//; Frequency                 = 912.400 MHz
//; Xtal Frequency            = 26.0000 MHz
//; Demodulation              = FSK
//; AGC                       = On
//; Data Rate                 = 2.4 kbps
//; Deviation                 = 10.0 kHz
//; Tx Xtal Tol.              = 20 ppm
//; Rx Xtal Tol.              = 20 ppm
//; TRx Matching Network Type = 20 dBm
//; Tx Power                  = +20 dBm
//; Gaussian BT               = NA
//; Bandwidth                 = Auto-Select kHz
//; CDR Type                  = Counting
//; CDR DR Range              = NA
//; AFC                       = On
//; AFC Method                = Auto-Select
//; Data Representation       = 0:F-low 1:F-high
//; Rx Duty-Cycle             = Off
//; Tx Duty-Cycle             = Off
//; Sleep Timer               = Off
//; Sleep Time                = NA
//; Rx Timer                  = Off
//; Rx Time T1                = NA
//; Rx Time T2                = NA
//; Rx Exit State             = STBY
//; Tx Exit State             = STBY
//; SLP Mode                  = Disable
//; RSSI Valid Source         = PJD
//; PJD Window                = 8 Jumps
//; LFOSC Calibration         = On
//; Xtal Stable Time          = 155 us
//; RSSI Compare TH           = NA
//; Data Mode                 = Packet
//; Whitening                 = Disable
//; Whiten Type               = NA
//; Whiten Seed Type          = NA
//; Whiten Seed               = NA
//; Manchester                = Disable
//; Manchester Type           = NA
//; FEC                       = Disable
//; FEC Type                  = NA
//; Tx Prefix Type            = 0
//; Tx Packet Number          = 1
//; Tx Packet Gap             = 32
//; Packet Type               = Variable Length
//; Node-Length Position      = First Node, then Length
//; Payload Bit Order         = Start from msb
//; Preamble Rx Size          = 2
//; Preamble Tx Size          = 8
//; Preamble Value            = 170
//; Preamble Unit             = 8-bit
//; Sync Size                 = 4-byte
//; Sync Value                = 768880084
//; Sync Tolerance            = None
//; Sync Manchester           = Disable
//; Node ID Size              = NA
//; Node ID Value             = NA
//; Node ID Mode              = None
//; Node ID Err Mask          = Disable
//; Node ID Free              = Disable
//; Payload Length            = 20
//; CRC Options               = None
//; CRC Seed                  = NA
//; CRC Range                 = NA
//; CRC Swap                  = NA
//; CRC Bit Invert            = NA
//; CRC Bit Order             = NA
//; Dout Mute                 = Off
//; Dout Adjust Mode          = Disable
//; Dout Adjust Percentage    = NA
//; Collision Detect          = Off
//; Collision Detect Offset   = NA
//; RSSI Detect Mode          = Always
//; RSSI Filter Setting       = No Filtering
//; RF Performance            = High
//; LBD Threshold             = 2.4 V
//; RSSI Offset               = 26
//; RSSI Offset Sign          = 1

//;---------------------------------------
//;  The following are the Register contents
//;---------------------------------------

		

byte CMT_Bank[12] = {
#if 0
0x00,
0x66,
0xEC,
0x1D,
0xF0,
0x80,
0x14,
0x08,
0x91,
0x02,
0x02,
0xD0,
#endif
0x00,
0x66,
0xEC,
0x1D,
0x70,
0x80,
0x14,
0x08,
0x11,
0x02,
0x02,
0x00,
};

//[System Bank]
byte System_Bank[12] = {
#if 0
0xAE,
0xE0,
0x35,
0x00,
0x00,
0xF4,
0x10,
0xE2,
0x42,
0x20,
0x00,
0x81,
#endif
//#if 0
0xAE,
0xE0,
0x35,
0x00,
0x00,
0xF4,
0x10,
0xE2,
0x42,
0x20,
0x00,
0x81,
//#endif
};

//[Frequency Bank]
byte Frequency_Bank[8] = {
#if 0
 0x46,
0x3A,
0x4D,
0x83,
 0x46,
0x2F,
0xF4,
0x12,
#endif
//#if 0
0x42,
0xCF,
0xA7,
0x8C,
0x42,
0xC4,
0x4E,
0x1C,
//#endif
};

//[Data Rate Bank]
byte Data_Rate_Bank[24] = {
#if 0
 0x32,
 0x18,
0x10,
 0x99,
0xC2,
0xBD,
0x06,
0x0B,
0x9F,
 0x26,
0x29,
0x29,
0xC0,
0x51,
 0x2A,
0x53,
0x00,
0x00,
0xB4,
0x00,
0x00,
0x01,
0x00,
0x00,
#endif
//#if 0
0x1F,
0xF8,
0x21,
0x10,
0x72,
0x12,
0x1F,
0x0A,
0x9F,
0x6C,
0x29,
0x29,
0xC0,
0x08,
0x02,
0x53,
0x18,
0x00,
0xB4,
0x00,
0x00,
0x01,
0x00,
0x00,
//#endif
};

//[Baseband Bank]
byte Baseband_Bank[29] = {
#if 0
0x12,
0x08,
0x00,
0xAA,
0x06,
0x00,
0x00,
0x00,
0x00,
0xD4,
0x2D,
0xD4,
0x2D,
0x01,
0x13,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x60,
0xFF,
0x00,
0x00,
0x1F,
0x10,
#endif

//#if 0	
0x12,
0x08,
0x00,
0x55,
0x06,
0x00,
0x00,
0x00,
0x00,
0xDE,
0x51,
0x0B,
0x93,
0x00,//0x05,
0x1F,
0x00,
0x00,
0x00,
0x00,
0x00,
0x03,
0xFF,
0xFF,
0x60,
0xFF,
0x00,
0x00,
0x1F,
0x10,
//#endif
};

//[TX Bank]
byte TX_Bank[11] = {
#if 0
0x50,
0x26,
 0x03,
0x00,
0x42,
0xB0,
0x00,
0x8A,
0x18,
0x3F,
0x7F,
#endif
//#if 0
0x70,
0xC0,
0x0F,
0x00,
0x02,
0x30,
0x00,
0x8A,
0x18,
0x3F,
0x7F,
//#endif
};


